- SAI/overlay/saidash.h
- SAI/underlay/saihostif.h
- SAI/underlay/saimirror.h
- SAI/underlay/saineighbor.h
- SAI/underlay/saipolicer.h
- SAI/underlay/saiport.h
- SAI/underlay/sairoute.h
- SAI/underlay/sairouterinterface.h
- SAI/underlay/saiswitch.h
> Add SAI API

- documents/SDN-Features-Packet-Transforms.md
> mm-sdn-features

- documents/media/images/README.md
> mm-media-dir-org-images.md

- documents/Program Scale Testing Requirements - Draft.md
> mm-sdn-pgm-test-reqs-toc

- test/docs/dash-test-workflow-p4-saithrift.md
Text for the P4 Simulator section. No need to review/comment, just merge it in (if acceptable) and cleanup/edit from there.
> Add prose. And cons.

- doc-github-rules.md
This PR addresses the following work items:
> mm-doc-github-rules.md

- sirius-pipeline/pna.p4
- sirius-pipeline/sirius_conntrack.p4
- sirius-pipeline/sirius_inbound.p4
- sirius-pipeline/sirius_outbound.p4
- sirius-pipeline/sirius_pipeline.p4
> PNA compatible connection tracking

- sirius-pipeline/README.md
Fixed typos and corrected instructions in sirius-pipeline README file
> Fixed typos and corrected instructions in sirius-pipeline readme file

- documentation/general/design/dash-sonic-hld.md
1. Added a section for design considerations
2. Added a section for example configuration
3. Fixed some schema objects based on review comments on Yang PR
> [Sonic] HLD update for dash-sonic

- documentation/general/design/dash-sonic-hld.md
Fixed some typo/errors in dash-sonic-hld document
> Fixed some typo/errors in dash-sonic-hld document

- dash-pipeline/bmv2/dash_inbound.p4
- dash-pipeline/bmv2/dash_pipeline.p4
> Remove inbound VM table

- .github/workflows/dash-ci.yml
- test/requirements.txt
Fixes https://github.com/Azure/DASH/issues/153 "ixia-c tests can fail if protobuf already installed with incompatible version"
> Use snappi 0.7.38

- dash-pipeline/SAI/sai_api_gen.py
Fixes Issue:
https://github.com/Azure/DASH/issues/144
> Fix duplicate appends in SAI API generator

- dash-pipeline/SAI/sai_api_gen.py
- dash-pipeline/SAI/templates/saiapi.h.j2
- dash-pipeline/bmv2/dash_acl.p4
- dash-pipeline/bmv2/dash_metadata.p4
- dash-pipeline/bmv2/dash_pipeline.p4
1) Support for 5 stage v4 and v6 ACL group IDs driven from ENI table as specified in the GNMI schema.
2) New ACL group table and change name of ACL table to ACL_RULE table.
3) Change P4 key match type to "optional" to trigger generation of Priority attribute in SAI API.
Adds/removes the following SAI attributes
```
New ACL group table -
/**
* @brief Attribute ID for dash_acl_dash_acl_group
*/
typedef enum _sai_dash_acl_group_attr_t
{
SAI_DASH_ACL_GROUP_ATTR_START,
/**
* @brief Action set_acl_group_attrs parameter IP_ADDR_FAMILY
* @type sai_ip_addr_family_t
* @flags CREATE_AND_SET
* @default SAI_IP_ADDR_FAMILY_IPV4
*/
SAI_DASH_ACL_GROUP_ATTR_IP_ADDR_FAMILY = SAI_DASH_ACL_GROUP_ATTR_START,
SAI_DASH_ACL_GROUP_ATTR_END,
SAI_DASH_ACL_GROUP_ATTR_CUSTOM_RANGE_START = 0x10000000, …
```
> ACL group attach/detach to ENI

- dash-pipeline/bmv2/dash_outbound.p4
> Remove 'nh_' from direct route's overlay_nh_ip

- dash-pipeline/bmv2/dash_pipeline.p4
> Move underlay SIP resolution to VIP table

- documentation/vnet2vnet-service/design/vnet-to-vnet-service.md
Per @prsunny correction to vnet-to-vnet
> Correction to vnet-to-vnet.md

- documentation/general/dash-sonic-hld.md
* Added "_TABLE" suffix to APP_DB tables that were missing that
Signed-off-by: Prabhat Aravind <paravind@microsoft.com>
> Update APP_DB table names

- README.md
> documentation-folder-reorg-link-fixes 

- documentation/general/dash-sonic-hld.md
- documentation/general/program-scale-testing-requirements-draft.md
- documentation/general/sdn-features-packet-transforms.md
Made some updates based on feedback on CPS and oversubscription capabilities.
> Yusef cps scalenumbers and oversubscription update

- dash-pipeline/SAI/templates/saiapi.cpp.j2
- dash-pipeline/SAI/templates/utils.cpp.j2
- dash-pipeline/tests/saithrift/ptf/vnet/test_saithrift_vnet.py
1. Fix duplicate SAI ID
2. Wrong search action
3. Double delete entry if SAI write error
4. Wrong format of error message
Signed-off-by: Ze Gan <ganze718@gmail.com>
> Fixbug: SAI Server crash on DASH ACL API

- .wordlist.txt
- test/test-cases/README.md
- test/test-cases/scale/vnet2vnet/README.md
- test/test-cases/scale/vnet2vnet/one-ip/README.md
Signed-off-by: Anton Putria <antonx.putria@intel.com>
> Fixed links in the README after renaming folders.

- documentation/general/dash-sonic-hld.md
Add ST/PL scenarios to Sonic HLD
Examples with packet forwarding.
> [Sonic] Add ST/PL scenarios to Sonic HLD

- test/test-cases/functional/ptf/sai_dash_utils.py
- test/test-cases/functional/ptf/saidashacl.py
- test/test-cases/functional/ptf/saidashvnet.py
Moved VnetObjects and VnetAPI from saidahvnet.py and placed it in sai_dash_utils.py
Signed-off-by: Yuriy Harhas <yuriyx.harhas@intel.com>
> Added sai_dash_utils module with common functions for VNET testing

- test/docs/README.md
Previous dev branches moved/disappeared. Links now point to master branch.
> Fix links to external SAI PTF documents.

- dash-pipeline/Makefile
- test/test-cases/functional/ptf/run-tests.sh
- test/test-cases/run-functional-tests.sh
Added options:
- SAI Server IP address
- Paths to port map and port config files
- Underlay/Overlay tests selection
- Hardware/BMv2 selection
- Interfaces specifing
Signed-off-by: Yuriy Harhas <yuriyx.harhas@intel.com>
> Updated run-functional-tests.sh

- test/test-cases/functional/ptf/run-tests.sh
- test/test-cases/functional/ptf/saidasheni.py
- test/test-cases/functional/ptf/saidashvnet.py
- Added a new option to set exact test target name
- Added a new option to control traffic direction in tests
- Updated skipifs
Signed-off-by: Yuriy Harhas <yuriyx.harhas@intel.com>
> Updated run-tests script for functional/ptf tests

- dash-pipeline/dockerfiles/DOCKER_SAI_CHALLENGER_CLIENT_BLDR_IMG.env
- dash-pipeline/dockerfiles/Dockerfile.saichallenger-client
From major updates:
- Fixed CRUD Get OP for Thrift Client
- Fixed CRUD Create OP for Thrift Client to return proper status on failure
> Updated SAI-Challenger to latest main

- documentation/general/dash-sonic-hld.md
Added a section for:
1. ACL requirements and expectations
2. ACL tagging behavior
3. ACL counters
> [Sonic] ACL tagging and requirements

- .github/workflows/pre-commit-check.yml
- .pre-commit-config.yaml
added pre-commit and pre-commit ci to check for file line endings and update them to linux if needed
to be merged in after https://github.com/sonic-net/DASH/pull/379 gets merged
> check that all files have linux line endings before commit

- dash-pipeline/README.md
Update to include Draft gap analysis for interested volunteers to participate.
> Update Pipeline README.md

- .gitmodules
- dash-pipeline/SAI/sai_api_gen.py
- dash-pipeline/SAI/templates/saifixedapis.cpp.j2
Update the SAI refpoint to OCP master end of June.
Also, update the sai_api_gen.py script to account for duplicate enums and those which are already part of saitypesextensions.h file
> Update SAI refpoint to OCP SAI

- documentation/general/dash-sonic-hld.md
1. Clarify metering precedence
2. Change ACL tag bitmap to list
> [Sonic] Update HLD for ACL tagging and metering

- .wordlist.txt
- documentation/general/dash-sonic-hld.md
Fastpath Sonic Design/Requirement clarifications.
> [Sonic-HLD] Update for Fastpath design and requirements

- dash-pipeline/SAI/sai_api_gen.py
- dash-pipeline/SAI/templates/saifixedapis.cpp.j2
Update fixed apis, and add missing ones
> Update fixed apis

- dash-pipeline/SAI/templates/saifixedapis.cpp.j2
> [submodule] Update SAI submodule to origin/master

- dash-pipeline/SAI/sai_api_gen.py
- dash-pipeline/SAI/templates/Makefile.j2
- dash-pipeline/SAI/templates/dashsai.cpp.j2
- dash-pipeline/SAI/templates/dashsai.h.j2
- dash-pipeline/SAI/templates/saiapi.cpp.j2
- dash-pipeline/SAI/templates/saifixedapis.cpp.j2
- dash-pipeline/SAI/templates/saiimpl.h.j2
- dash-pipeline/SAI/templates/utils.cpp.j2
- dash-pipeline/SAI/templates/utils.h.j2
Many changes:
* Move utils to it's own namespace dash::utils 
* Move fixed api implementation to proper DashSai class
* Remove unused methods
* Add workaround to return not supported status on get api 
* Remove underscore from variable naming
* Fix route bulk api set/get warnings
* Simplify insertInTable method
* Change asserts to return error codes and add missing switch api
* Print oids in hex form
> [SAI] Refactor SAI and add new features to be compatible with sonic-sairedis 

- dash-pipeline/SAI/src/dashsai.cpp
- dash-pipeline/SAI/templates/saiapi.cpp.j2
Using metadata add generic code to obtain attr name and log it when
attr is not supported for better debugging
> [libsai] Add attr name logging when doing get api

- dash-pipeline/SAI/templates/saiapi.cpp.j2
https://github.com/sonic-net/DASH/issues/415
> [SAI] wrong code generated in libsai #415

- .wordlist.txt
- documentation/general/dash-sai-pipeline-packet-flow.md
This change is related to issue: #456.
> Fix wrong word in allowed word list.

- dash-pipeline/SAI/sai_api_gen.py
- dash-pipeline/SAI/templates/saiapi.h.j2
- dash-pipeline/SAI/templates/saienums.j2
No update to all generated files:
```bash
$ diff SAI/lib ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib  
```
> Remove unnecessary variable for enum member parser and rename paramAction and objectName for better naming convention.

- dash-pipeline/SAI/sai_api_gen.py
- dash-pipeline/bmv2/README.md
- dash-pipeline/bmv2/dash_acl.p4
- dash-pipeline/bmv2/dash_pipeline.p4
- dash-pipeline/bmv2/underlay.p4
No changes to generated contents as below, using the latest main as baseline:
```bash
$ diff SAI/SAI/inc ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/SAI/inc 
$ diff SAI/lib ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib 
```
> [sai-gen] Update Sai attribute doc to include the latest support values, also split it into SaiVal and SaiTable for better clarity.

- dash-pipeline/bmv2/dash_conntrack.p4
- dash-pipeline/bmv2/dash_outbound.p4
- dash-pipeline/bmv2/dash_pipeline.p4
Same as previous sai generator changes, no changes on the generated files:
```bash
$ diff SAI/lib/ ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib/
```
> [sai-gen] Remove unnecessary name annotations in P4 code.

- dash-pipeline/SAI/sai_api_gen.py
Add type hints to make the code more maintainable since it will be even less likely to go wrong.
As previous refactoring changes, no updates on generated files:
> [sai-gen] Add type hints for SAI generation scripts.

- documentation/general/dash-sonic-hld.md
Addressing minor cosmetic issues
> Fix typos and section numbering in hld

- dash-pipeline/SAI/src/sai_dash_buffer.cpp
- dash-pipeline/SAI/src/sai_dash_dtel.cpp
- dash-pipeline/SAI/templates/saiimpl.h.j2
Needed to return dummy success object to for new dash-app
> [SAI] Add dummy buffer and dtel api

- dash-pipeline/SAI/src/sai_dash_buffer.cpp
- dash-pipeline/SAI/src/sai_dash_dtel.cpp
- dash-pipeline/SAI/templates/saifixedapis.cpp.j2
- dash-pipeline/SAI/templates/saiimpl.h.j2
- dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp
Fix api query for buffer and dtel
> [dash-sai] Fix buffer and dtel

- dash-pipeline/SAI/src/objectidmanager.cpp
Update OID format to support new extensions range base More info in PR: https://github.com/opencomputeproject/SAI/pull/2028
> [dash-sai] Update object id manager to support extensions range

- test/test-cases/functional/saic/tutorial/README.md
small change correct path is `DASH/....` for `cd`
> path update in docs

- dash-pipeline/bmv2/stages/outbound_mapping.p4
- dash-pipeline/bmv2/stages/outbound_routing.p4
default size is 1024 increased mapping to 8M and routing to 4M
> increase table size to accommodate full dash hero scale

- dash-pipeline/SAI/src/sai_dash_buffer.cpp
Update SAI to latest master to have dash flow update.
> [sai] Update SAI submodule to the latest

- dash-pipeline/dockerfiles/Dockerfile.saichallenger-client-bldr
Update SAI-Challenger @ f249b33 to latest master
dpugen 0.0.5 to 0.2.3
> Update dpugen to 0.2.3 and saic to latest master

- documentation/general/program-scale-testing-requirements/README.md
clarification for https://github.com/sonic-net/DASH/issues/397
> clarification for Calculation error in program scale testing requirements?
