sirius-pipeline/sirius_acl.p4, sirius-pipeline/sirius_conntrack.p4, sirius-pipeline/sirius_headers.p4, sirius-pipeline/sirius_inbound.p4, sirius-pipeline/sirius_metadata.p4, sirius-pipeline/sirius_outbound.p4, sirius-pipeline/sirius_parser.p4, sirius-pipeline/sirius_pipeline.p4, sirius-pipeline/sirius_service_tunnel.p4, sirius-pipeline/sirius_vxlan.p4
=> Add pipeline definition

documentation/general/design/dash-handling-fragmented-packets.md
Updated tuple which is used to uniquely identify a temporal flow.  Also, couple of minor edits to the document
=> Updated tuple which is used to uniquely identify a temporal flow.

sirius-pipeline/bmv2/sirius_inbound.p4, sirius-pipeline/bmv2/sirius_metadata.p4, sirius-pipeline/bmv2/sirius_outbound.p4, sirius-pipeline/bmv2/sirius_pipeline.p4
Make ENI mapping from inner MAC direction agnostic
by copying the right MAC to metadata before the
lookup.
Note: This does not change the behavior of the
pipeline, but simplifies the API generated based
on it.
=> Consolidate MAC to ENI mapping

documentation/general/design/dash-sonic-hld.md
Docker daemon memory usage was measured without running containers.
It might be confusing because it doesn't reflect real docker daemon
memory usage when all containers are running. Memory used by the Docker
daemon can be calculated by the following:
"all used memory" - "memory used by all docker containers" - "base OS memory".
=> Remove docker daemon from memory footprint.

dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_pipeline.p4
=> Add ENI admin state

dash-pipeline/Makefile, dash-pipeline/README.md
Fixes https://github.com/Azure/DASH/issues/143.
Executes `chmod `as required. Permanent fix will require some Docker mods.
Note, instead of `make clean all` please use `make clean && make all` to ensure `chmod` gets called prior to both make targets.
Reviewers, please clone the dev branch and try fresh `make clean && make all network run-switch` to validate this works for other users. I've tested as another alias user and it worked, but I prefer independent testing. Thanks!
=> Temporary workaround for container permissions issues 

test/docs/README.md
SAI PTF User Guide was upstreamed. Changing link from dev branch to main branch.
=> Update link to SAI PTF User Guide

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4
Support for remaining Phase 1 routing actions as specified in the Sonic HLD / Vnet-Vnet doc.
Fixes issue #134
It generates following additional SAI attributes.
```
/**
* @brief Attribute data for #SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION
*/
typedef enum _sai_outbound_routing_entry_action_t
{
SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_VNET,
SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_VNET_DIRECT,    
SAI_OUTBOUND_ROUTING_ENTRY_ACTION_ROUTE_DIRECT,
SAI_OUTBOUND_ROUTING_ENTRY_ACTION_DROP,
} sai_outbound_routing_entry_action_t;
typedef enum _sai_outbound_routing_entry_attr_t
{
SAI_OUTBOUND_ROUTING_ENTRY_ATTR_START,
SAI_OUTBOUND_ROUTING_ENTRY_ATTR_ACTION = SAI_OUTBOUND_ROUTING_ENTRY_ATTR_START,
/**
     * @brief Action route_vnet, route_vnet_direct parameter DEST_VNET_VNI
     *
     * @type …
```
=> Dash Routing: Direct, Vnet_direct and Drop action support

dash-pipeline/bmv2/dash_headers.p4, dash-pipeline/bmv2/dash_parser.p4
**Summary of PR**
Right now, if you send an ipv4 packet with an optional header to the pipeline, the parser will fail because it will try to extract UDP/TCP immediately after plain ipv4 header. This PR adds support for IPv4 options in the parser/deparser.
**How it was tested?** @chrispsommers 
1. Since this changeset is only related to parser/deparser, I temporarily emptied out the dash-pipeline such that is simply sends every packet coming from port 0 out to port 1
2. Bring up the setup and send different packets with/without ipv4 options to veth0
3. Examine the logs of simple_switch to verify the functionality of parser
4. Examine the contents of packets coming out of veth2 to verify the functionality of deparser
=> Add support for IPV4 optional headers

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/SAI/templates/utils.cpp.j2, dash-pipeline/SAI/templates/utils.h.j2, dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp, dash-pipeline/tests/saithrift/ptf/vnet/test_saithrift_vnet.py, dash-pipeline/tests/saithrift/pytest/vnet/test_saithrift_vnet.py
Populate SAI obj-id as P4 match key.
No change in SAI API headers.
Fixes #166 
```
docker exec -w /tests/libsai/vnet_out simple_switch-mukesh ./vnet_out
GRPC call SetForwardingPipelineConfig 0.0.0.0:9559 => /etc/dash/dash_pipeline.json, /etc/dash/dash_pipeline_p4rt.txt
GRPC call Write::INSERT OK
GRPC call Write::INSERT OK
GRPC call Write::INSERT OK
GRPC call Write::INSERT OK
GRPC call Write::INSERT OK
GRPC call Write::INSERT OK
GRPC call Write::DELETE OK
GRPC call Write::DELETE OK
GRPC call Write::DELETE OK
GRPC call Write::DELETE OK
GRPC call Write::DELETE OK
GRPC call Write::DELETE OK
Done.
```
```
Match key:
* hdr.vxlan.vni:VNI   : EXACT     3c0000
Action entry: dash_ingress.set_outbound_direction -
[01:04:43.937] [bmv2] [D] [thread 40] Entry 0 added to table …
```
=> Fix SAI object create error in libsai adapter

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp, dash-pipeline/tests/saithrift/ptf/vnet/test_saithrift_vnet.py, dash-pipeline/tests/saithrift/pytest/vnet/test_saithrift_vnet.py
- ENI table drives vnet-id for the VNET table as specified in the GNMI
schema
- Route lookup drives destination vnet-id for the VNET table lookup
- Removing redundant eni_to_vni table
=> Adding vnet table to the pipeline

.github/workflows/dash-bmv2-ci.yml, .gitmodules
At this moment, all changes required to run SAI PTF Thrift tests on devices with fewer ports (like DASH devices) are done in dev repos. Meanwhile the changes are upstreaming into main SAI/PTF repos, changing CI to use this development repo to be able to run PTF tests now. Once all PTF/SAI Thrift changes are merged, this submodule needs to be changed back to use mainstream SAI repo.
Signed-off-by: Volodymyr Mytnyk <volodymyrx.mytnyk@intel.com>
=> CI: Use repo/branch with SAI PTF DASH support

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/dash_pipeline.p4
Classify inbound packet to VNET instead of using VNI
as VNIs alone may overlap
=> Fix inbound VNET routing classification

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/tests/saithrift/ptf/vnet/test_saithrift_vnet.py, dash-pipeline/tests/saithrift/pytest/echo/test_echo_port.py
Fixes part of #147
Handle all table miss drops consistently at the end of the pipeline
Fixes #177 
SAI API change - Removes the following action
`
SAI_INBOUND_ROUTING_ENTRY_ACTION_DENY 
`
Could not added defaultonly tag to the drop action in the vip and pa_validation tables as this removes all SAI attributes for these APIs. SAI does not support apis with no attributes. Ran into the following metadata check errors when this was attempted
```
ERROR: enum sai_vip_entry_attr_t is empty, after removing suffixed entries _START/_END/_RANGE_BASE
ERROR: enum sai_pa_validation_entry_attr_t is empty, after removing suffixed entries _START/_END/_RANGE_BASE
```
or this when I removed the sai_xxx_attr_t enum completely.
```
ERROR: SAI_OBJECT_TYPE_VIP_ENTRY is not defined in OBJTOAPIMAP, missing …
```
=> Default drop support for P4 table miss without generating SAI drop action

.github/workflows/dash-bmv2-bldr-docker-acr.yml, .github/workflows/dash-saithrift-bldr-docker-acr.yml, .github/workflows/dash-saithrift-bldr-docker.yml, .github/workflows/dash-saithrift-client-bldr-docker-acr.yml, dash-pipeline/Makefile
Build processes which publish to ACR must be run from DASH repo or a branch; forks don't have access to ACR secrets. This incremental commit pushes changes to DASH `publish-dockers-to-acr` branch to result in publishing and consuming all docker images using Azure Container REgistry (ACR).
Some actions will fail on the first pass until images get published, because they pull from same ACR registry. It's a chicken-and-egg problem which will be solved in subsequent changes.
=> Publish docker images to ACR and use those in build process.

dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/dash_pipeline.p4
Fixes #147 task 2 allowing to add @defaultonly tag to vip and pa_validation table deny actions
SAI api header change - removes the following actions
```
SAI_VIP_ENTRY_ACTION_DENY
SAI_PA_VALIDATION_ENTRY_ACTION_DENY
```
=> SAI apigen support for tables with no action parameters and a single action

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/utils.cpp.j2, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/tests/libsai/Makefile, dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp
Make APIs compatible with SONiC bulk infra
=> Split SAI API

.wordlist.txt, dash-pipeline/Makefile, dash-pipeline/README-dash-workflows.md, dash-pipeline/SAI/saithrift/Makefile
when building a vendor specific libsai.so to link into the saithrift server, we might need extra libraries to finalize the saiserver executable, e.g. dependency on google protocol buffer specific library.
by setting a new environment variable, the dash-pipeline makefile will make sure that
1/ this variable is passed via docker to the saithrift server docker run
2/ the saithrift server makefile uses this env variable to expand the linker compile flags.
example usage from thirdparty makefile
SAIRPC_VENDOR_EXTRA_LIBS="/dash/dash-pipeline/SAI/lib/libprotobuf.a"
thirdparty-saithrift-server: thirdparty-libsai
@echo "Build third-party saithrift-server"
@echo "   Expects libsai.so under $(DASHDIR)/dash-pipeline/SAI/lib"
SAIRPC_VENDOR_EXTRA_LIBS=$(SAIRPC_VENDOR_EXTRA_LIBS) $(MAKE) -C …
=> allow vendor specific lib for saithrift server compile

dash-pipeline/README-saithrift.md, dash-pipeline/bmv2/dash_acl.p4, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_parser.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/dash_vxlan.p4
Added IPv6 ACL support for DASH
=> IPv6 ACL support for DASH

dash-pipeline/bmv2/dash_pipeline.p4
Make inbound direction a default of a table
Remove the deny option from SAI API as a result
=> Remove deny action from direction lookup

dash-pipeline/dockerfiles/Dockerfile.bmv2-bldr, dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr
Two Dockerfiles used some base images in `FROM` clauses and they hadn't gotten changed to use ACR, this fixes that omission. No functional changes.
=> Replace chrissommers dockerhub with sonicdash.azurecr.io (missed in PR225)

dash-pipeline/SAI/sai_api_gen.py
=> Change list match to prefix list for IPs

test/docs/testplans/eni.md, test/test-cases/functional/ptf/saidasheni.py
- Added ENI verification test plan.
- Added automated ENI tests.
- Moved all common functions to sai_dash_utils.py
- Skipped failing tests on CI.
=> Dash ENI create/remove tests

dash-pipeline/SAI/templates/saiapi.cpp.j2
Get the following warning due to a wrong conversion from pointer to value
```
saidashacl.cpp: In function 'sai_status_t sai_create_dash_acl_group(sai_object_id_t*, sai_object_id_t, uint32_t, const sai_attribute_t*)': saidashacl.cpp:96:21: warning: invalid conversion from 'sai_object_id_t*' {aka 'long unsigned int*'} to 'sai_object_id_t' {aka 'long unsigned int'} [-fpermissive]
RemoveFromTable(dash_acl_group_id);
^~~~~~~~~~~~~~~~~
In file included from saidashacl.cpp:9:
utils.h:227:38: note:   initializing argument 1 of 'bool RemoveFromTable(sai_object_id_t)'
bool RemoveFromTable(sai_object_id_t id);
~~~~~~~~~~~~~~~~^~
saidashacl.cpp: In function 'sai_status_t sai_create_dash_acl_rule(sai_object_id_t*, sai_object_id_t, uint32_t, const sai_attribute_t*)':
saidashacl.cpp:828:21: warning: …
```
=> Fix warning: wrong conversion from pointer to value

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.h.j2
Generate ADDR_FAMILY attribute to object types
that have IP address as part of it's key.
This is a read-only attribute used by resource
availability API.
=> Add ADDR_FAMILY attr generation

test/test-cases/functional/ptf/saidasheni.py, test/test-cases/functional/saic/sai-api/test_sai_api_vnet_out_route.py
the vni passed in saidasheni.py was incorrect
the outbound route needs to be removed before the ENI (reverse order of create)
=> minor fixes (passed value and removal ordering) in testcases

test/test-cases/functional/saic/test_vm_to_vm_commn_acl_inbound.py, test/test-cases/functional/saic/test_vm_to_vm_commn_acl_outbound.py, test/test-cases/functional/saic/test_vm_to_vm_commn_udp_bidir.py, test/test-cases/functional/saic/test_vm_to_vm_commn_udp_inbound.py
This PR fixes SAI-C CI issue caused by https://github.com/sonic-net/DASH/pull/339
In case TC setup process fails at some step, we should not try to remove all entries on teardown because some of them were not created. For known issues, the simplest solution is to replace `xfail` with `skip`.
=> Skipping SAI-C TCs affected by issues/345

.wordlist.txt, dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_acl.p4, dash-pipeline/bmv2/dash_pipeline.p4
Add support for @sai[] structured annotations for
table keys and action parameters. If not available, the old 
way is still valid till all params and keys will be annotated.
=> Support SAi attr generation from annotattions

documentation/general/program-scale-testing-requirements-draft.md
- background tcp flows 15M (was 1M)
- background udp flows 15M (was 1M)
- background traffic packet size reduced to 500B from 1500B
- total flow capacity reduced by half (down to 32M from 64M) -
Signed-off-by: Mircea Dan <mircea-dan.gheorghe@keysight.com>
=> update to scale numbers

dash-pipeline/Makefile, dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr
when libsai.so is created with a compiler version that is newer than what is run within the saithrift builder docker container, we may run into unresolved linkage error (such as unresolved __libc_single_threaded).
however, if the compiler is older, we are fine.
so we need to upgrade the distro used within the saithrift build docker image.
more generically, this change allows to provide the ubuntu SHA to be used by docker to build the image from the calling Makefile.
by default, we'll use a 22.04 ubuntu version, but this can be overridden by setting AMD64_UBUNTU_SHA256 to the wanted hash.
=> update saithrift-bld Dockerfile to accept the ubuntu image SHA as ARG

dash-pipeline/SAI/templates/saiapi.cpp.j2
=> SAI bulk add/remove implementation

.wordlist.txt, documentation/general/dash-sonic-hld.md
- "vnet" is not needed when the action "direct" is configured.
=> [doc] Update configuration example for "DASH_ROUTE_TABLE" entries with action "direct"

dash-pipeline/dockerfiles/DOCKER_SAI_CHALLENGER_CLIENT_BLDR_IMG.env, dash-pipeline/dockerfiles/Dockerfile.saichallenger-client, dash-pipeline/dockerfiles/Dockerfile.saichallenger-client-bldr, dash-pipeline/tests/requirements.txt, test/requirements.txt
This new version of SAI-Challenger auto-generates `sai_thrift_metadata.py` in run-time.
Fixes Issue https://github.com/sonic-net/DASH/issues/374
=> Updated SAI-Challenger to latest main as of May 30

dash-pipeline/SAI/templates/saifixedapis.cpp.j2, dash-pipeline/SAI/templates/utils.cpp.j2, dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp
For future passing parameters via service method table
@lguohan @marian-pritsak @Pterosaur @chrispsommers please review
=> [SAI] Move constructor to sai_api_initialize

documentation/general/dash-sonic-hld.md, documentation/general/program-scale-testing-requirements-draft.md
ENIs per 200G link reduced to 32 from 64
adjusted CPS value in HLD to match the hero test
increased flow timer from 1 sec to 5 sec ( to reduce PPS requirements for BG traffic)
=> DASH scale requirement update

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/Makefile.j2, dash-pipeline/SAI/templates/config.cpp.j2, dash-pipeline/SAI/templates/config.h.j2, dash-pipeline/SAI/templates/saidash.h.j2, dash-pipeline/SAI/templates/saifixedapis.cpp.j2
Adding this support will allow syncd to easy pass configuration parameters to dash libsai using service method table
=> [SAI] Add support for dash configuration from sai interface

dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/SAI/templates/saifixedapis.cpp.j2, dash-pipeline/SAI/templates/utils.cpp.j2, dash-pipeline/SAI/templates/utils.h.j2, dash-pipeline/tests/libsai/init_switch/init_switch.cpp
Couple changes:
* fix NextObjIndex and rename to NextObjectId, which embeds correct object type, this will be needed in sai_object_type_query
* fix dome log messages in get_switch_attribute
* move GetDeviceId to static, since no longer required to be public
* fix init_switch.cpp, since previously was using GetDeviceId to init GRPS channel, now  this is done inside sai_api_initialize
=> [SAI] Fix NextObjIndex method to embed objeect type into generated OID

dash-pipeline/bmv2/underlay.p4, test/test-cases/scale/saic/test_sai_vnet_route_bidirectional.py, test/test-cases/scale/saic/test_sai_vnet_route_unidirectional.py, test/test-cases/scale/saic/vnet_route_setup_commands_bidirectional.json, test/test-cases/scale/saic/vnet_route_setup_commands_unidirectional.json
**Description of PR**
This subsequent PR is the continuation of dash_underlay implementation PR #404  in BMv2 of the design mentioned in the dash hld under swss lite.
The focus of this PR is on introducing the implementation of SAI call for "SAI_ROUTE_ENTRY_ATTR_PACKET_ACTION" 
The attribute implemented is "SAI_ROUTE_ENTRY_ATTR_PACKET_ACTION". In this PR we have added support for packet action types "SAI_PACKET_ACTION_DROP" and "SAI_PACKET_ACTION_FORWARD". 
**Functionality**
In the current implementation, when there is no match in the routing table, the packet continues to be reflected on the same port and when a route is matched in the routing table, the packet is directed to a different port as specified by the matching route.
This PR decides whether to drop or forward the packet first. …
=> Adds SAI_ROUTE_ENTRY_ATTR_PACKET_ACTION api to dash_underlay_routing

dash-pipeline/SAI/sai_api_gen.py
This will make easier for make pick up when file actually changed
=> [sai-api-gen] Write files only when changes are detected

dash-pipeline/Makefile, dash-pipeline/SAI/saithrift/Makefile, dash-pipeline/SAI/templates/Makefile.j2, dash-pipeline/SAI/templates/dashsai.cpp.j2, dash-pipeline/SAI/templates/saifixedapis.cpp.j2, dash-pipeline/tests/libsai/init_switch/.gitignore, dash-pipeline/tests/libsai/init_switch/Makefile, dash-pipeline/tests/libsai/init_switch/init_switch.cpp, dash-pipeline/tests/libsai/vnet_out/.gitignore, dash-pipeline/tests/libsai/vnet_out/Makefile
* compile everything with host user id and group
* reduce number of required libs
* simplify Makefiles
* make proper dependencies
=> [dash-pipeline] Refactor Makefiles

dash-pipeline/Makefile
p4 depends on 
P4_ARTIFACTS=$(P4_OUTDIR)/dash_pipeline.json $(P4_OUTDIR)/dash_pipeline_p4rt.txt
the makefile was modified to include a P4_ARTIFACTS rule. this means that 2 identical parallel docker runs will be launched (one for each of the files) causing an issue when compiling p4 (DOCKER_FLAGS= make -j p4)
the fix is to create a rule for the json file (to depend on p4rt) and update the docker run rule to be for the p4rt file.
=> update p4 compile dependency to avoid parallel identical docker runs for both the json and the p4rt.txt

dash-pipeline/Makefile, dash-pipeline/SAI/debian/.gitignore, dash-pipeline/SAI/debian/Makefile, dash-pipeline/SAI/debian/libsai-dev_1.0.0_amd64/DEBIAN/control, dash-pipeline/SAI/debian/libsai_1.0.0_amd64/DEBIAN/control, dash-pipeline/SAI/debian/libsai_1.0.0_amd64/DEBIAN/shlibs, dash-pipeline/SAI/debian/libsai_1.0.0_amd64/DEBIAN/triggers
Will create libsai and libsai-dev packages for usage in other projects
=> [dash] Add libsai-debs target to create libsai debian packages

dash-pipeline/Makefile, dash-pipeline/SAI/saithrift/Makefile
Also compile libsaimetadata.so, so it wont be compiled as objects into saithrift server anymore, it will be used as external library
=> [SAI] Update SAI submodule to the latest origin/master

documentation/general/dash-sonic-hld.md
This PR is for issue https://github.com/sonic-net/DASH/issues/452.
The IP is incorrectly placed there. From the DASH policy below, the right IP is 10.1.1.1.
```
{
"DASH_VNET_MAPPING_TABLE:Vnet1:10.1.1.1": {
"routing_type":"vnet_encap",
"underlay_ip":"101.1.2.3",
"mac_address":"F9-22-83-99-22-A2",
"metering_class":"1001"
},
"OP": "SET"
},
```
=> Fix incorrect IP in SONiC-DASH HLD VNET to VNET example.

dash-pipeline/SAI/src/Makefile, dash-pipeline/SAI/src/sai_dash_router_interface.cpp
For better catching mistakes and bugs
=> [dash-SAI] Enable warnings as errors

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/bmv2/dash_outbound.p4
This makes code more explicit on 0 = v4 and 1 = v6.
This change will not change any generated code. Here is the diff for proof. Only comment update after make:
```bash
$ diff SAI/lib ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib/
diff SAI/lib/saidashoutboundcatopa.cpp /home/r12f/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib/saidashoutboundcatopa.cpp
47c47
<         // set is_ipv6_field_id field
---
>         // set v4_or_v6 field
241c241
<         // set is_ipv6_field_id field
---
>         // set v4_or_v6 field
diff SAI/lib/saidashoutboundrouting.cpp /home/r12f/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib/saidashoutboundrouting.cpp
45c45
< …
```
=> Rename is_*_v4_or_v6 to *_is_v6.

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/dash_outbound.p4
With these changes, we will be able to specify the enum types and default value for any table key and action parameter as below:
```
@Sai[type="sai_dash_encapsulation_t", default_value="SAI_DASH_ENCAPSULATION_VXLAN"]
dash_encapsulation_t dash_encapsulation,
```
This removes the dependency on the variable name which has to match with the type.
This leads below code change which makes the generated SAI matches what is in opencompute SAI:
```bash
diff SAI/SAI/experimental/saiexperimentaldashoutboundrouting.h /home/r12f/data/code/sonic/DASH-exp/dash-pipeline/SAI/SAI/experimental/saiexperimentaldashoutboundrouting.h
206c206
<      * @default …
```
=> [sai-gen] Simplify type solving, move enum type solving to use Sai attribute, add default value in Sai attribute

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_acl.p4, dash-pipeline/bmv2/dash_outbound.p4
This PR moves acl table to use `@SaiTable` annotation instead of `@name`.
After the change, SAI headers will be generated exactly the same:
```bash
```
However, due to name is changed in P4, the table id will be changed, but it only affects the libsai generated from DASH for testing, not any providers' implementation.
```bash
$ diff SAI/lib ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib              
diff SAI/lib/saidashacl.cpp /home/r12f/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib/saidashacl.cpp
211c211
<     // For stage acl.stage1
---
>     // For stage inbound_acl_stage1
213c213
< …
```
=> [sai-gen] Move acl table to use SaiTable annotation.

.wordlist.txt, dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_acl.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/underlay.p4
This PR has 2 updates:
1. Deprecate the `@name` annotations in favor of `@SaiTable`.
2. Add `api_order` attribute in `@SaiTable` annotation to help us enforce the order of the generated APIs.
The second change is a must have, otherwise for any API set that contains multiple type of entries (generated from multiple tables), the order could be changed between changes and break the ABI compatibility as the screenshot shows below:
The doc is also updated to capture the use of this new attribute.
For generated content updates:
1. No updates on SAI header files:
```bash
```
2. For libsai, table id …
=> [sai-gen] Deprecate the name annotations in favor of SaiTable

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_acl.p4, dash-pipeline/bmv2/dash_conntrack.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/underlay.p4
This change is based on #479 , hence including all changes in the PR.
No update on SAI headers after this change:
```bash
```
2 comments are updated in lib file, but looks like the previous result is wrong:
Take route_vnet as an example, it indeed only take 4 parameters, as ip_is_v6 field doesn't count:
=> [sai-gen] Deprecate name attribute for all match keys and action parameters, remove type guessing heuristics on object parent names.

dash-pipeline/SAI/sai_api_gen.py
No update in the generated content:
```bash
$ diff SAI/lib/ ~/data/code/sonic/DASH-exp/dash-pipeline/SAI/lib/
```
=> [sai-gen] Use the first value of enum as default value.

dash-pipeline/SAI/sai_api_gen.py
With all the previous changes, now we can finally remove these logics.
=> [sai-gen] Remove all complicated logic when parsing p4runtime object names.

dash-pipeline/SAI/sai_api_gen.py
The range match is frequently used for cases like port ranges and etc.
This change doesn't change anything in the pipeline, but only add the functionality support for future cases.
More can be found in:
- DASH packet flow: https://github.com/sonic-net/DASH/blob/main/documentation/general/dash-sai-pipeline-packet-flow.md
- Usage in SAI ACL (not DASH): https://github.com/opencomputeproject/SAI/blob/master/inc/saiacl.h
- SAI types: https://github.com/opencomputeproject/SAI/blob/master/inc/saitypes.h
=> [sai-gen] Add range match type support in SAI generation script.

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/dash_acl.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4
Moved this logic to use "isobject" annotation explicitly.
As all previous sai generator changes, no update on the generated contents:
=> [sai-gen] Remove SAI object guessing logic based on number of match keys.

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_acl.p4, test/test-cases/functional/ptf/saidashacl.py
This PR changes 3 things:
1. Update the type annotation of ACL table match keys, so we can generate the right types for ACLs.
2. Add `match_type` annotation for match keys, so we can fix the `optional` match kind that we use to make P4 compiler happy.
3. Update SAI header generation script to handle the new annotation.
The end results is shown as below. The comment and type are now updated to the same as opencompute SAI:
(no changes showing up in git diff)
To compare with previous generated content:
- Header files:
```bash
diff SAI/SAI/experimental/saiexperimentaldashacl.h /home/r12f/data/code/sonic/DASH-exp/dash-pipeline/SAI/SAI/experimental/saie …
```
=> [sai-gen] Update ACL tables type and match type annotations for SAI header generation

dash-pipeline/SAI/sai_api_gen.py
The following highlighted empty lines are missing for new types:
Fix is straightforward, simply adding a line break in. The newly added line break will be ignored when checking the existing ones, which is already handled by existing code. Only the line break is missing.
=> [sai-gen] Fix missing empty lines when generating new SAI API type and object types

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.h.j2
Currently, the default value of each SAI attribute is specified in saiapi.h.j2 template, using if-else. This can be simplified by directly using the default value from the type info in SAI generation script.
This change also makes adding more SAI types easier in the future, for both existing types or new types (just like new enums today, we only need to register it to type registry, then everything else will be taken care of).
=> [sai-gen] Move default value from template to SAI generation script.

dash-pipeline/Makefile
p4c-bm2-ss is a dedicated compiler built for building bmv2 code. Unlike p4c-ss and p4c-bm, this compiler is using the latest code, directly built from the p4c backend. 
Switching to this compiler will not change the generated content, but it will give us more access on more command line options instead of being limited to the small set of the parameters provided by p4c, e.g. dumping IRs, which may give us more information for generating SAI in a more smarter way.
Similarly, we are already doing it for DPDK - using p4c-dpdk instead of p4c -b dpdk.
=> [build] Switch BMv2 p4 compiler from p4c to p4c-bm2-ss.

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_pipeline.p4
Today, how DASH generates SAI API for counters is via mock action parameters.
One example is shown as below, where the counters are not updated by the meter_bucket_action, however we need to generate SAI APIs for fetching these counters. Hence, 2 action parameters that is marked as readonly are added for this purpose.
```c
#define MAX_METER_BUCKETS 262144
#ifdef TARGET_BMV2_V1MODEL
counter(MAX_METER_BUCKETS, CounterType.bytes) meter_bucket_inbound;
counter(MAX_METER_BUCKETS, CounterType.bytes) meter_bucket_outbound;
#endif // TARGET_BMV2_V1MODEL
action meter_bucket_action(
@SaiVal[type="sai_uint64_t", isreadonly="true"] bit<64> outbound_bytes_counter,
@SaiVal[type="sai_uint64_t", isreadonly="true"] bit<64> inbound_bytes_counter,
@SaiVal[type="sai_uint32_t", skipattr="true"] bit<32> …
```
=> [sai-gen] Add P4 counter parsing support in SAI generation script and remove mock counter attributes in DASH pipeline

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_acl.p4, dash-pipeline/bmv2/dash_pipeline.p4
Currently, DASH SAI attributes are generated based on the order of table keys and action parameters. When multiple types of objects are mixed together, adding a new attributes could cause new SAI attributes being inserted in the middle of the attribute list and breaks the ABI compatibility.
This change introduces 2 things:
- adds `order` attribute in `@SaiVal` annotation, so we could sort the attributes in the way that keeps the ABI compatibility.
- renames `api_order` to `order` in `@SaiTable` annotation, to keep the naming the same way.
The current change will not change the generated content today, as screenshot shows below:
=> [sai-gen] Add order annotation for attributes to support ordering SAI attributes for ABI compatibility

documentation/README.md
Link was missing the https at the front.
=> Fix Broken Link in Documentation for PINS

dash-pipeline/SAI/Makefile, dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/dockerfiles/Dockerfile.saithrift-bldr
Currently, the SAI attributes will be generated from table keys, action parameters and counters. Table keys and action parameters are naturally connected to the tables directly or indirectly in the P4 runtime json. However, counters are not, so we don't have enough information to find which SAI API we should add the attribute.
To solve this, we have already added an annotation in SaiCounter, to specify the action names, so we can correlate the counters and its tables. However, this is tedious to do, if we have a lot of counters to add.
This change parses the P4 IR json file to find which action this counter has been called to, so we can associate the counters and its action and tables automatically. 
Take an example, say we add a new counter in the metering action to calculate total …
=> [sai-gen] Make SAI generator understand P4 IR to fetch counter references / callers.

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/dash_pipeline.p4
Currently, SAI API generation is not leveraging the counter type information, but blindly use whatever specified in the `name` annotation. This leads to 2 problems:
1. We could accidentally generate incorrect SAI headers, e.g. name says it is a byte counter, but in fact it is a packet counter in our BM. 
2. We could not support counters that tracks multiple things, i.e. packets and bytes.
This change uses the type info in the counter to generate the correct SAI attributes, also fork the counter when the single counter in BM tracks multiple things.
As the screenshot shows below, after the change, if we change the counter type of the meter_bucket_outbound, a new SAI attribute will be created for it.
This change will not change any of existing SAI header files that we generated, but can be …
=> [sai-gen] Add support to packets and packet_and_bytes counters, also make counter generation to be adaptive to its type.

dash-pipeline/SAI/sai_api_gen.py
Currently, DASH only supports generating counters as SAI attributes upon DASH APIs, such as metering buckets. This might be ok for new things that has dedicated DASH concepts, i.e., metering buckets. However, for other more generic counters used for collecting telemetry, this approach could leads to feature missing and not fully utilizing what we already have in SAI and SONiC. For example, no get-and-reset operation support and need to build dedicated pipeline for pulling the counters and feeds them into the telemetry.
This change adds support to generate the counters as [SAI generic counters](https://github.com/opencomputeproject/SAI/blob/master/doc/SAI-Proposal-Generic-Counters.md). Instead of generate the counters as readonly attributes, we generate a counter id for it. Then, we can …
=> [sai-gen] Add counter id generation support for counters.

dash-pipeline/bmv2/dash_outbound.p4
Replace dst_addr with src_addr as a sip parameter.
=> Fix set_private_link_mapping

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saicounter.j2
Currently, whenever a counter is used in a control block and not associated to any tables, we won't be able to handle the SAI header generation for it, although we know this counter will be mostly used for tracking the DPU level counts.
This change adds counter id generation support on port level. Whenever the above case happens, a new counter id attribute will be generated on port level.
Take an example - if we add a counter to track total bytes in DASH as below:
The following counter id attribute will be generated:
=> [sai-gen] Add counter id generation support on port level

dash-pipeline/Makefile, dash-pipeline/README-dash-as-submodule.md, dash-pipeline/README-dash-workflows.md, dash-pipeline/README.md, test/third-party/traffic_gen/deploy_ixiac.sh, test/third-party/traffic_gen/deployment/README.md, test/third-party/traffic_gen/undeploy_ixiac.sh
Fixes #510 
As a secondary effect this also enables the use of Podman, as it emulates `docker compose` but not `docker-compose`.
=> [docker] Change to using Docker Compose v2

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/headers/sai_api_comment_object_id.j2, dash-pipeline/SAI/templates/headers/sai_api_param_object_id.j2, dash-pipeline/SAI/templates/headers/sai_stats_api.j2, dash-pipeline/SAI/templates/headers/sai_stats_api_list.j2, dash-pipeline/SAI/templates/headers/sai_stats_enum.j2, dash-pipeline/SAI/templates/headers/sai_stats_extensions.j2, dash-pipeline/SAI/templates/saiapi.cpp.j2, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/SAI/templates/saicounter.j2, dash-pipeline/SAI/templates/saistat.j2, dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_pipeline.p4
DASH has scaling requirement that requires technology providers to support huge number of objects, e.g. 8M of CA-PA mappings. If we need to add counters for these objects by using generic SAI counters, we will generate large number of counter ids, which might not be ideal.
Also some counters we are collecting are not data path counters, but more like hit counts, which is not what generic SAI counter is modeling.
For these cases, we can support generating the counters as SAI stats and leverage existing SAI stats API design for querying the counters back.
This change updated sai_api_gen.py with 2 changes:
1. Rename `as_attr` to `attr_type` for supporting more types of counter generation.
2. Updated the counter generation logic and its templates for generating SAI stats APIs.
This feature …
=> [sai-gen] Add support for generating SAI stats APIs for counters.

documentation/general/dash-sonic-hld.md
- Add `routing_appliance_id` field to VNET mapping table
- Update PL encoding format
- Remove 'key' attribute in routing type table in favor of 'vni'
- Fix SIP encodings in PL example
=> Update HLD for PL scenario

dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_outbound.p4
The service tunnel key is a dead code and never used in building the encapsulation.
Assign the tunnel key to VNI will fix this issue.
=> [dash-p4] Fix incorrect service tunnel key assignment.

dash-pipeline/bmv2/dash_arch_specific.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4
This is to simplify the code for creating and attaching the direct counters.
No SAI updates will be introduced with this change.
=> [dash-p4] Create macro for creating direct counters

documentation/general/dash-sonic-hld.md
1. Add Route group table for grouping routes and binding to an ENI
2. Introduce PA validation table for special validation for certain scenarios
=> [Dash-Sonic] Introduce route group, pa validation tables

dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/dash_routing_types.p4, dash-pipeline/bmv2/stages/outbound_mapping.p4, dash-pipeline/bmv2/stages/outbound_routing.p4
Currently, the routing types in DASH is used to define 2 things: 
- Stage transition: which stage we need to run as the next stage
- Routing actions: what SDN transformations are required if this stage is the last stage used to match the packets.
Although the concepts are there, in DASH P4 code, these concepts are not reflected in a modularized way, and sometimes not that obvious as the transition cannot be found in the definitions of the routing types (P4 table actions).
This commit contains 2 changes inside:
- Add skeleton for matching stage transition control
- Extract the matching stages in outbound pipeline into dedicated file
These changes are intended to help with:
- Modularization and readability of the pipeline.
- Make the stage transition control more explicit and obvious.
This …
=> [dash-p4] Add skeleton for matching stage transition control and extract the matching stages in outbound pipeline into dedicated file.

dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/stages/direction_lookup.p4, dash-pipeline/bmv2/stages/eni_lookup.p4, dash-pipeline/bmv2/stages/metering_update.p4
This change is a straightforward code refactor that moves direction lookup, eni lookup and metering update stage into dedicated files.
This change will not update any SAI API headers.
=> [dash-p4] Modularize direction lookup, eni lookup and metering update stages.

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/bmv2/dash_arch_specific.p4
In today's DASH SAI generator, we support 3 type of counters: SAI counter ID, SAI Attributes and SAI stats. Due to the nature of P4 counters, the counters are used as packet counters or byte counters, hence all counters will either have _PACKET or _BYTES suffix.
However, we have many counters that doesn't work as packet counters, for example - how many flows is created or deleted.
This change updates the SAI generator to support the counters without suffix. This allows us to support generating hit-count type counters.
For example, if we have these counters defined in P4:
The following stats will be generated on the ENI:
=> [sai-gen] Add support of generating hit count counters

dash-pipeline/bmv2/dash_conntrack.p4, dash-pipeline/bmv2/dash_inbound.p4, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_routing_types.p4
The original overlay dip/sip looks to be redundant and can directly reuse the overlay data we already have in the metadata, hence doing this change.
=> [dash-p4] Remove original overlay IP from encap data and reuse the existing fields.

dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_pipeline.p4
Preserve is the default, there is no condition under which INVALID can be set.
=> Remove INVALID mode from DSCP modes

dash-pipeline/SAI/src/Makefile, dash-pipeline/SAI/src/objectidmanager.h
Got the following compiling errors in a local environment
```
g++ -I../SAI/meta -I../SAI/inc -I../SAI/experimental  -ansi -fPIC -pipe -std=c++11 -Wall -Wcast-align -Wcast-qual -Wconversion -Wdisabled-optimization -Werror -Wextra -Wfloat-equal -Wformat=2 -Wformat-non
literal -Wformat-security -Wformat-y2k -Wimport -Winit-self -Wno-inline -Winvalid-pch -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wno-aggregate-retur
n -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-aliasing=3 -Wswitch -Wswitch-default -Wunreachable-code -Wunused -Wvaria
dic-macros -Wwrite-strings -Wno-switch-default -Wconversion -Wno-psabi -Wno-unused-label -MMD -c dashsai.cpp -o dashsai.o …
```
=> misc: Fix compiling issue in local environment

dash-pipeline/SAI/debian/Makefile
We want to install the libsai debian package into SONiC. The libsai with p4 pipeline configuration is one to one mapping. So this configuration should also be added to the package.
=> [debian]: Add p4 pipeline json to libsai debian package

dash-pipeline/bmv2/dash_tunnel.p4
We found this issue while running one of the inbound routing PTF tests in saidashvnet.py. Most likely the bug was introduced during refactoring of tunnel encapsulation code.
In case of inbound routing, overlay_dmac is not supposed to be modified. But, in inbound_routing.p4, when tunnel_encap action is called, the value of meta.overlay_data.dmac is zero and tunnel_encap action ends up incorrectly setting the overlay_dmac to zero.
`        
tunnel_encap(hdr,
meta,
meta.overlay_data.dmac,
meta.encap_data.underlay_dmac,
meta.encap_data.underlay_smac,
meta.encap_data.underlay_dip,
meta.encap_data.underlay_sip,
dash_encapsulation_t.VXLAN,
meta.encap_data.vni);
`
This fix will check for a non-zero overlay_dmac value before overwriting the customer dmac field in the packet header.
=> Check for valid overlay_dmac value before overwriting the field in the header

test/test-cases/functional/ptf/run-tests.sh, test/test-cases/functional/ptf/sai_dash_utils.py, test/test-cases/functional/ptf/saidashvnet.py
- Run tests in "monodir" mode since bidirectional testing requires stateful connection tracking and learning of new flows in both directions.
- Fixed IP address mask in more tests
- Comment out underlay programming since dash.p4 doesn't have a complete implementation of underlay.
=> VNET test fixes

dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/tests/libsai/vnet_out/vnet_out.cpp, test/test-cases/functional/saic/config_bidir_setup_commands.py, test/test-cases/functional/saic/config_inbound_setup_commands.py, test/test-cases/functional/saic/config_outbound_setup_commands.json, test/test-cases/functional/saic/sai-api/test_sai_api_vnet_eni_addr.py, test/test-cases/functional/saic/tutorial/test_sai_vnet_outbound_small_scale_config_via_dpugen_create.json, test/test-cases/scale/saic/vnet_inbound_setup_commands.json, test/test-cases/scale/saic/vnet_outbound_setup_commands_scale.json, test/test-cases/scale/saic/vnet_outbound_setup_commands_simple.json, test/test-cases/scale/saic/vnet_route_setup_commands_bidirectional.json, test/test-cases/scale/saic/vnet_route_setup_commands_unidirectional.json
Currently, we have a very complicated check for when a table action should be generated, for example:
The reason of this check being introduced is to enable us ignore the `SAI_VIP_ENTRY_ACTION_DENY` and `SAI_PA_VALIDATION_ENTRY_ACTION_DENY` action while still keep the action generated for them, as these entries only has 1 action which will be ignored.
However, this check is too narrowed, and also create some issues, for example - an object (not entry) with 1 action will also have the action type generated, which is not ideal.
Ideally, the condition to generate the action type should be really straightforward:
1. If the table entry has more than 2 valid actions (not deny), the action type should be generated.
2. If the table entry is an entry, not object, the action type should be …
=> [sai-gen] Simplify condition for table action generation.

dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_outbound.p4, dash-pipeline/bmv2/dash_routing_types.p4, dash-pipeline/bmv2/stages/outbound_pre_routing_action_apply.p4
This change adds a pre routing action apply stage, which serves as a pivot for doing any post processing after routing and mapping stages before the final action being applied.
=> [dash-p4] Add pre-routing action apply stage.

dash-pipeline/SAI/templates/saiapi.h.j2
When we create a new SAI object (table) without any attribute and with the counter attached, the counter id will be generated as the first attribute, however the format is not right, as it doesn't have the ` = SAI_TABLE_NAME_ATTR_START` part after it. This will cause SAI checkers to fail.
This change fixes the template, so we can have the counter attribute correctly generated as below in this case.
```c
typedef enum _sai_some_table_attr_t
{
/**
* @brief Start of attributes
*/
SAI_SOME_TABLE_ATTR_START,
/**
* @brief Attach a counter
*
* When it is empty, then packet hits won't be counted
*
* @type sai_object_id_t
* @flags CREATE_AND_SET
* @objects SAI_OBJECT_TYPE_COUNTER
* @allownull true
* @default SAI_NULL_OBJECT_ID
*/
SAI_SOME_TABLE_ATTR_COUNTER_ID = SAI_SOME_TABLE_ATTR_START,
/**
* …
```
=> [sai-gen] Fix SAI generation if the coutners is the firs attribute.

dash-pipeline/bmv2/dash_pipeline.p4
The SAI action type generation follows the order of the actions defined in P4 and the first one will be the default action. The newly added tunnel decap actions in inbound routing table are not used as default value, as they are put in the end of the action list.
This change fixes the action order, which produces the right default action in the SAI header:
=> [sai-gen] Update the default action of inbound routing type to use the latest one instead of deprecated one.

dash-pipeline/SAI/templates/headers/sai_stats_enum.j2
SAI has a style checker that forces the certain words to be upper cases in the comment, such as acronyms like ENI. However, currently we are generating the comments using lower cases, which breaks this checker.
This issue will be gone after moving everything to upper case, hence making this change to fix this issue.
=> [sai-gen] Fix template for generating the SAI stats.

dash-pipeline/SAI/src/dashsai.cpp, dash-pipeline/SAI/src/dashsai.h, dash-pipeline/SAI/templates/saiapi.cpp.j2
When calling create function, populate attributes that have
default value present to overcome BMv2 limitations.
=> [dash-pipeline] Populate attributes with default values

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/headers/sai_stats_api.j2, dash-pipeline/SAI/templates/headers/sai_stats_enum.j2
We have the metering API, flow resimulation API, HA state management and inline sync APIs, and more updates all merged into OCP SAI. This change brings the updates back to DASH, so we can see the latest differences.
=> [sai] Update SAI to latest master

documentation/high-avail/ha-api-hld.md
The initial HA session API added the support of HA state machine management and support of configurating data plane channel for inline sync. And this change added the API to support bulk sync.
From SAI point of view, the bulk sync works as below:
1. On the source side, a flow API will be called to create the bulk sync session with specified conditions, which points to a certain destination, which can either be the swbusd in the control plane for flow relay or the paired DPU directly.
2. Once session is created, the source DPU will start to connect to the destination w/ a gRPC server and send the flow record across.
3. Once session is done, optionally the connection can be closed.
Hence, in the API, we will see 2 major things being added:
- On HA set attributes, the control plane channel …
=> [doc] Add bulk sync support in HA session API.

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/saiapi.h.j2, dash-pipeline/bmv2/stages/ha.p4
This change updates the P4 code to generate the SAI APIs for bulk sync API, flow reconcile API and related counters.
The API change can be found via the PR in OCP SAI repo here: https://github.com/opencomputeproject/SAI/pull/2014.
=> [dash-p4] Support SAI API generation for bulk sync API, flow reconcile API and related counter.

documentation/high-avail/ha-api-hld.md
The flow reconcile API is for helping unplanned failover to avoid SDN policy going backwards. 
Basically, whenever the DPU/ENI enters a role that does flow decision from a role that doesn't do it. It needs to stop flow resimulation for existing flows, even upon request. Until the flow reconcile request is called explicitly, when SDN controller confirms the latest policies are programmed, the flow resimulation can be resumed.
Because the flow reconcile goes with the DPU/ENI, the attributes are added on the HA scope level. Besides attributes, we also added an event notification for requesting flow reconcile from the DASH implementation.
=> [doc] Add flow reconcile APIs in the HA session API.

documentation/high-avail/ha-api-hld.md
Packet drops is one of the major common problem in network that needs to be monitored. This change adds the drop counters that we need to monitor in DASH pipeline.
Since the drop counters are not too complicated and also could be counted as part of the HA design, hence we are adding them as part of the HA API doc.
=> [doc] Include drop counters in HA API.

dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/stages/eni_lookup.p4, dash-pipeline/bmv2/stages/outbound_mapping.p4, dash-pipeline/bmv2/stages/outbound_routing.p4, documentation/high-avail/ha-api-hld.md
This change follows the drop counter HLD to add the drop counters into DASH p4 code for generating the drop counters on port stats and ENI stats.
The detailed HLD is here: https://github.com/sonic-net/DASH/pull/563.
=> [dash-p4] Update DASH p4 code for generating the drop counters.

dash-pipeline/bmv2/dash_counters.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/stages/eni_lookup.p4, dash-pipeline/bmv2/stages/ha.p4, dash-pipeline/bmv2/stages/outbound_mapping.p4, dash-pipeline/bmv2/stages/outbound_routing.p4
Moving the global and ENI counters from all over the places to a dedicated file, because they are special and working more like "global" counters, and spread across the pipeline.
This helps us to have a better view and helps us maintaining the ABI compatibility of these counters.
The other counters will go with its table, such as HA set, because they are only used in logic that is related to that single table.
=> [dash-p4] Refactor global and ENI counter definitions.

dash-pipeline/SAI/templates/saiapi.h.j2
There is a change directly committed to OCP SAI to make the DASH SAI APIs working better for SAI explorer. However, this change is not updated into DASH repo, which means all future SAI API updates from DASH could override it and any new APIs will not be covered.
To help with this, this change updates the SAI API template to have a better naming.
For references, the original OCP PR is here: https://github.com/opencomputeproject/SAI/pull/1971.
=> [dash-sai] Update SAI API template to make SAI explorer working better.

dash-pipeline/Makefile, dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/specs/dash_outbound_ca_to_pa.yaml, dash-pipeline/SAI/specs/dash_outbound_routing.yaml, dash-pipeline/SAI/specs/dash_tunnel.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/SAI/utils/sai_spec/sai_api.py, dash-pipeline/SAI/utils/sai_spec/sai_api_extension.py, dash-pipeline/SAI/utils/sai_spec/sai_api_group.py, dash-pipeline/SAI/utils/sai_spec/sai_api_p4_meta.py, dash-pipeline/SAI/utils/sai_spec/sai_attribute.py, dash-pipeline/SAI/utils/sai_spec/sai_common.py, dash-pipeline/SAI/utils/sai_spec/sai_enum.py, dash-pipeline/SAI/utils/sai_spec/sai_enum_member.py, dash-pipeline/SAI/utils/sai_spec/sai_spec.py, dash-pipeline/SAI/utils/sai_spec/sai_spec_utils.py, dash-pipeline/SAI/utils/sai_spec/sai_struct.py, dash-pipeline/SAI/utils/sai_spec/sai_struct_entry.py
This change added the SAI spec merging support. This is to ensure any new SAI attribute changes will follow the rules below to help ABI compatibility:
- All new attributes or action enum values will be added in the end of the list.
- Existing attributes will be updated inline. In the future, we can add more check here, e.g., type changed in non-compatible way and etc.
- All old attributes will be marked as deprecated instead of removed.
Recently, the tunnel APIs are added, but because it merged with the SAI spec PR together without rebase, it is not captured in the previous SAI spec. With SAI spec merging, we can see the changes are showing up in the expected sequence. This would be an example that demos the several usages of SAI spec.
=> [sai-gen] Support merging SAI specs.

dash-pipeline/SAI/src/utils.cpp, dash-pipeline/SAI/src/utils.h, dash-pipeline/SAI/templates/saiapi.cpp.j2
1.To set a default IPv6 route with the prefix 0, we will get following error logs. It's caused by the limitation of p4lang: https://github.com/p4lang/PI/blob/24e0a3c08c964e36d235973556b90e0ae922b894/proto/frontend/src/device_mgr.cpp#L2242-L2246 .
```
2024 Jun  3 15:26:21.033130 vlab-01 ERR syncd#syncd_dash: e:- mutateTableEntry: GRPC ERROR[2]: , #010#002#032¡#001#012#037type.googleapis.com/p4.v1.Error#022~#010#003#022gInvalid reprsentation of 'don't care' LPM match, omit match field instead of using a prefix length of 0#032#021ALL-sswitch-p4org
2024 Jun  3 15:26:21.033130 vlab-01 ERR syncd#syncd_dash: e:- mutateTableEntry: GRPC call Write::INSERT ERROR: table_id: 49279256 match { field_id: 1 lpm { value: "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000" } } action { …
```
=> Skip default IPv6 route with prefix zero and fix IPv6 prefix bug

dash-pipeline/SAI/utils/sai_spec/sai_spec.py
Since P4 compiler won't maintain the order of the generated enums in p4runtime, it causes all enum values moves around in the code review. Since the enum types from P4 doesn't have any dependencies to each other, we can merge the new enum values into the current SAI spec by appending to the end of the list, just like other SAI attributes.
Additionally, to maintain the SAI ABI, we will not remove any existing enum values too.
=> [sai-gen] Maintaining the order of SAI enum types.

dash-pipeline/bmv2/README.md, dash-pipeline/bmv2/dash_arch_specific.p4, dash-pipeline/bmv2/dash_counters.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/stages/ha.p4
Since we can now use SAI spec to handle the order of all attributes and APIs, we don't need to explicit specify the order anymore. Hence, removing it from the P4 code.
After all orders are removed, `make sai-header` locally will not cause any SAI API change as below:
```
r12f@r12f-dl380:~/code/sonic/DASH/dash-pipeline/SAI/SAI
$ gst
On branch temp
Your branch is up to date with 'origin/temp'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
bm/
nothing added to commit but untracked files present (use "git add" to track)
```
The order attribute in the SaiTable annotation still needs to be kept, because the lib generation will require it to be present to generate the API initialization code correctly.
=> [dash-p4] Deprecate order attribute on SaiVal and SaiCounter annotations.

.github/workflows/dash-bmv2-ci.yml, dash-pipeline/Makefile
To help the code review of SAI header updates, update the CI workflow to ensure we have up-to-date SAI spec included in the PR.
This is achieved by checking git status and see if any changes in the SAI/specs folder, after running `make sai` in the CI pipeline.
=> [ci] Update CI to ensure SAI spec are generated and updated.

.wordlist.txt, dash-pipeline/SAI/specs/dash_eni.yaml, dash-pipeline/SAI/specs/dash_ha.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/stages/ha.p4, documentation/high-avail/ha-api-hld.md
This PR adds SAI API support for the DPU scope DPU driven Dash HA mode described in this PR. 
https://github.com/sonic-net/SONiC/pull/1710
In this mode, the HA scope / HA state is at the DPU level. Also the DPU vendor SDK owns the HA state machine and drives state transitions on its own by directly communicating with its HA pair underneath the SAI layer. The DPU SDK advertises HA state changes as SAI event notifications.
=> Add support for DPU scope DPU driven HA

dash-pipeline/SAI/specs/dash_outbound_ca_to_pa.yaml, dash-pipeline/SAI/specs/dash_outbound_routing.yaml
Some SAI APIs are merged during the effort of enabling the SAI spec, hence updating the spec manually to make them match.
=> Update the SAI specs to make it match with the latest merged SAI APIs

dash-pipeline/SAI/specs/dash_direction_lookup.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/stages/direction_lookup.p4, dash-pipeline/bmv2/stages/eni_lookup.p4, dash-pipeline/bmv2/stages/outbound_mapping.p4, dash-pipeline/bmv2/stages/outbound_routing.p4
This PR adds support to select which MAC address to use for looking up the ENI in the direction lookup stage.
This change follows the ExpressRoute gateway bypass HLD defined in this PR here: https://github.com/sonic-net/DASH/pull/601.
=> [dash-p4] Add ENI mac override support on direction lookup stage.

dash-pipeline/SAI/specs/dash_ha.yaml, dash-pipeline/bmv2/stages/ha.p4
Correct annotation tag typo (SalVal -> SaiVal) for action param `ha_set_id`. It generates correct type of `ha_set_id` in ha spec dash_ha.yaml and then in SAI header `saiexperimentaldashha.h`. In the end it fixes the issue https://github.com/opencomputeproject/SAI/issues/2057.
=> [ha] Fix action param ha_set_id annotation

dash-pipeline/SAI/specs/dash_flow.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/stages/conntrack_lookup.p4, documentation/dataplane/dash-flow-api.md
The term ENI_ADDR was found to be unclear, so we have updated it to ENI_MAC in both the code and documentation.
=> [dash-flow] Rename ENI_ADDR to ENI_MAC

dash-pipeline/SAI/Makefile, dash-pipeline/SAI/specs/dash_appliance.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_pipeline.p4
Corresponds to the local region id field added to the Appliance table schema [here](https://github.com/sonic-net/SONiC/pull/1783)
=> Add SAI appliance object, local region ID field

dash-pipeline/SAI/specs/dash_appliance.yaml, dash-pipeline/SAI/specs/dash_inbound_routing.yaml, dash-pipeline/SAI/specs/dash_pa_validation.yaml, dash-pipeline/SAI/specs/dash_vip.yaml, dash-pipeline/bmv2/dash_inbound.p4, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/stages/direction_lookup.p4, dash-pipeline/bmv2/stages/inbound_routing.p4, dash-pipeline/bmv2/stages/pre_pipeline.p4
Currently, several stages / tables in DASH directly uses the headers to lookup entries, such as direction. inbound routing, and etc. It it ok currently, because DASH only accepts traffic with a single layer and a single type of encap. However, once we start to handle multiple layers and types of encaps, it will make the pipeline very complicated.
This change refactors the pipeline to add a pre-pipeline stage to preprocess the underlay and overlay data for pipeline lookup and actions, so we can keep the rest of the pipeline more future-proof.
=> [dash-p4] Refactor incoming packet encap handling and inbound routing stage.

documentation/express-route-service/express-route-gateway-bypass.md
The current MSEE failover handling in ER gateway bypass design is reverse route table based, which is flexible, powerful, but a bit complicated. 
With this change, we are going to simplify the MSEE failover handling using tunnel learning. There are 1 minor issue we could not address with this design, but we will update the design later which is compatible with this design and having the problem solved.
=> [doc] Simplify MSEE failover handling in ER gateway bypass design.

dash-pipeline/SAI/specs/dash_eni.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_pipeline.p4
Per HLD update: https://github.com/sonic-net/DASH/pull/619. This PR adds the reverse tunnel information on ENI.
The packet transformation requires data plane app to create the flow, hence not included in this PR.
=> [dash-p4] Add attributes on ENI for reverse tunnel information.

dash-pipeline/SAI/src/dashsai.cpp, dash-pipeline/SAI/src/dashsai.h, dash-pipeline/SAI/templates/saiapi.cpp.j2
All bulk create/removal objects SAI implementation is essentially the same. Hence making some helper functions for simplify the generated libsai.
With more changes coming, we should be able to make the libsai templates and generations more maintainable.
=> [libsai] Make helper function for bulk object create and removal to simplify libsai generation.

dash-pipeline/SAI/debian/Makefile
Add shared library saimetadata to libsai debian package. Because when a program is linked to a sai library(such as dash sai), it should also be linked to the corresponding saimetadata library as well. Otherwise, there may be a risk of crashing if the sai library uses an attribute that is not in the saimetadata library.
=> [debian]: Add saimetadata to libsai debian package

dash-pipeline/SAI/specs/dash_flow.yaml, dash-pipeline/bmv2/stages/conntrack_lookup.p4
This PR adds `@SaiVal[type="sai_ip_address_t"]` before the following arguments of action `set_flow_entry_attr` in dash flow:
- underlay0_sip
- underlay0_dip
- underlay1_sip
- underlay1_dip
There are mainly two reasons for doing this:
- Other parts of the dash pipeline do so. For example, in action `set_eni_attrs`, every argument of type `IPv4Address` is added a `@SaiVal[type="sai_ip_address_t"]` before it.
- Generated saithrift rpc can use IP address-related helper functions to assign a value to corresponding arguments instead of directly using a u32 type value, making the code more readable.
=> [DASH Flow] Add SaiVal derivative before some arguments of set_flow_entry_attr to make configuration easier

dash-pipeline/Makefile, dash-pipeline/bmv2/defines.h, dash-pipeline/bmv2/stages/outbound_mapping.p4, dash-pipeline/bmv2/stages/outbound_routing.p4
This pull request adds a new header file `defines.h` for constants definitions. It defines different table sizes for outbound routing and ca_to_pa mapping according to [hero-implementation-details](https://github.com/sonic-net/DASH/blob/main/documentation/general/program-scale-testing-requirements/hero-implementation-details.md).
The hardcoded table sizes of outbound routing and ca_to_pa mapping, whose size 4M and 8M respectively (from https://github.com/sonic-net/DASH/pull/592) take up too much memory by default. This memory pressure could make low-RAM KVM DPU crash and be unusable with sonic mgmt test. 
The below shows the dash pipeline memory usage of the container `simple_switch` with different scale number of routing and mapping.
```
1. 4M/8M …
```
=> Define table size per scaling test 

dash-pipeline/bmv2/dash_headers.p4, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/stages/conntrack_lookup.p4, dash-pipeline/bmv2/stages/pre_pipeline.p4, dash-pipeline/dockerfiles/Dockerfile.saithrift-client-bldr, test/test-cases/functional/ptf/p4_dash_utils.py, test/test-cases/functional/ptf/saidashvnet_sanity.py
This PR adds a module p4_dash_utils to include helper functions for p4 pipeline. 
* Function `set_internal_config` aims to update pipeline internal configuration, neighbor mac, data port mac, cpu port mac, etc.
* Decorator `use_flow` aims to enable flow lookup stage in p4 pipeline. It wrappers method setUp/tearDown of test class.
=> [ptftest] Add p4_dash_utils

dash-pipeline/SAI/templates/saiapi.cpp.j2
Adjust the api locations, remove white spaces at the line end and remove blank lines, as to generate neat code.
Taking generated file SAI/lib/saidashoutboundrouting.cpp as an example, the side effect of this change is as below:
- Remove the useless comment and align the statement
- Move bulk APIs (create|remove)_outbound_routing_entries after quad APIs (create|remove|set|get)_outbound_routing_group_attribute
- Remove white space between function name and '('
=> [libsai] Tidy up saiapi.cpp.j2

dash-pipeline/SAI/sai_api_gen.py, dash-pipeline/SAI/templates/impls/p4_table_action.cpp.j2, dash-pipeline/SAI/templates/impls/p4_table_entry_match.cpp.j2, dash-pipeline/SAI/templates/impls/p4_table_object_match.cpp.j2, dash-pipeline/SAI/templates/impls/p4_table_util.cpp.j2, dash-pipeline/SAI/templates/impls/sai_api_func_bulk.cpp.j2, dash-pipeline/SAI/templates/impls/sai_api_func_quad.cpp.j2, dash-pipeline/SAI/templates/impls/sai_api_func_stats.cpp.j2, dash-pipeline/SAI/templates/impls/sai_api_group.cpp.j2, dash-pipeline/SAI/utils/sai_gen/__init__.py, dash-pipeline/SAI/utils/sai_gen/sai_generator.py, dash-pipeline/SAI/utils/sai_gen/sai_impl_generator.py
Base on https://github.com/sonic-net/DASH/pull/647, refactor the templates of libsai implementation
to make it more readable and maintainable. It replaces one single template `saiapi.cpp.j2` with several
small templates under directory `SAI/templates/impls`.
The changes will not change any generated cpp code for sai api implementation:
```
junhuazhai@junhuazhai-dev-vm:~/workspace/DASH/dash-pipeline$ diff -Nur -x '*.[od]' ~/DASH/dash-pipeline/SAI/lib/ SAI/lib
junhuazhai@junhuazhai-dev-vm:~/workspace/DASH/dash-pipeline$
```
=> [sai-gen] Refactor the templates of libsai implementation

dash-pipeline/bmv2/routing_actions/routing_action_encap_underlay.p4
Argument of `do_action_encap_u1` should be from `meta.u1_encap_data`. Previously, `meta.u0_encap_data` was used.
=> [Routing actions] Fix incorrect arguments in do_action_encap_u1

dash-pipeline/bmv2/dash_inbound.p4, dash-pipeline/bmv2/dash_pipeline.p4
The key of underlay routing lookup is meta.dst_ip_addr. It should be updated to underlay destination IP only if underlay1/0 encapsulation is taken.
=> [dash-p4] Correctly set meta.dst_ip_addr for underlay routing lookup

dash-pipeline/SAI/src/sai_dash_acl.cpp, dash-pipeline/SAI/templates/impls/p4_table_util.cpp.j2, dash-pipeline/SAI/templates/impls/sai_api_func_quad.cpp.j2, dash-pipeline/SAI/templates/saifixedapis.cpp.j2, dash-pipeline/SAI/templates/saiimpl.h.j2
1. Fix #655 , by adding dummy implementation for SAI_OBJECT_TYPE_ACL_TABLE
2. Fix #656, by bypassing creation of route entry with prefix length 0
=> [libsai] dummy implementation for ACL_TABLE

.github/workflows/dash-bmv2-ci.yml
While raising PRs, workflow dash-bmv2-ci will fail during job setup with the following error:
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/, that says:
> Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible.
=> [ci] Use actions/upload-artifact v4 in workflow dash-bmv2-ci

dash-pipeline/bmv2/dash_headers.p4, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/stages/conntrack_lookup.p4, dash-pipeline/dpapp/dash/flow.c, dash-pipeline/dpapp/dash/flow.h
Support customized flow idle timeout in flow creation. The value can be propagated from `flow_ttl_in_milliseconds` attribute of the flow table. Also update flow entry key selection from `flow_enabled_key` attribute of the flow table.
=> [dash-p4] Add flow idle timeout support in behavior model

dash-pipeline/SAI/specs/dash_eni.yaml, dash-pipeline/bmv2/dash_pipeline.p4, test/test-cases/functional/ptf/saidashdpapp_sanity.py
By adding `flow_table_id` attribute on ENI object, ENI can be associated with a specific flow table
=> [dash-p4] Add flow_table_id attribute on ENI

dash-pipeline/SAI/specs/dash_acl.yaml, dash-pipeline/SAI/specs/dash_appliance.yaml, dash-pipeline/SAI/specs/dash_direction_lookup.yaml, dash-pipeline/SAI/specs/dash_eni.yaml, dash-pipeline/SAI/specs/dash_flow.yaml, dash-pipeline/SAI/specs/dash_ha.yaml, dash-pipeline/SAI/specs/dash_inbound_routing.yaml, dash-pipeline/SAI/specs/dash_meter.yaml, dash-pipeline/SAI/specs/dash_outbound_ca_to_pa.yaml, dash-pipeline/SAI/specs/dash_outbound_routing.yaml, dash-pipeline/SAI/specs/dash_pa_validation.yaml, dash-pipeline/SAI/specs/dash_tunnel.yaml, dash-pipeline/SAI/specs/dash_vip.yaml, dash-pipeline/SAI/specs/dash_vnet.yaml, dash-pipeline/SAI/specs/route.yaml, dash-pipeline/SAI/src/p4meta.cpp, dash-pipeline/SAI/src/p4meta.h, dash-pipeline/SAI/src/utils.h, dash-pipeline/SAI/templates/impls/p4_table_entry_match.cpp.j2, dash-pipeline/SAI/templates/impls/p4_table_util.cpp.j2, dash-pipeline/SAI/utils/dash_p4/dash_p4_table.py, dash-pipeline/SAI/utils/sai_spec/sai_api_p4_meta.py
If at least one of the match fields is Optional, Ternary or Range, p4runtime v1 model requires 'priority' to be set for each table entry. But in some dash scenarios, 'priority' is not required and is not exposed to dash sai. For these special cases, we add a single_match_priority field in SaiTable annotation to mark it. If it is 'true', the behavior changes are: 
- Not generate attribute PRIORITY in SAI object
- Not generate field priority in SAI entry struct
- Set the priority of all table entries to a default (fixed) value 1 in dash p4 libsai
It also adds the set/get support of p4 match kind `range`.
=> Add single_match_priority in SaiTable annotation

dash-pipeline/SAI/specs/dash_eni.yaml, dash-pipeline/SAI/specs/dash_outbound_ca_to_pa.yaml, dash-pipeline/SAI/specs/dash_outbound_port_map.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/SAI/utils/sai_spec/sai_spec_utils.py, dash-pipeline/bmv2/dash_counters.p4, dash-pipeline/bmv2/dash_headers.p4, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_routing_types.p4, dash-pipeline/bmv2/routing_actions/routing_action_nat_port.p4, dash-pipeline/bmv2/routing_actions/routing_actions.p4, dash-pipeline/bmv2/stages/outbound_port_map.p4, dash-pipeline/bmv2/stages/outbound_pre_routing_action_apply.p4, dash-pipeline/bmv2/stages/routing_action_apply.p4, dash-pipeline/dpapp/dash/flow.h
PL redirect map implementation. HLD PR #664.
=> [dash-p4] Update P4 to support PL redirect map

dash-pipeline/SAI/specs/dash_direction_lookup.yaml, dash-pipeline/SAI/specs/dash_eni.yaml, dash-pipeline/SAI/specs/dash_trusted_vni.yaml, dash-pipeline/SAI/specs/sai_spec.yaml, dash-pipeline/bmv2/dash_counters.p4, dash-pipeline/bmv2/dash_metadata.p4, dash-pipeline/bmv2/dash_pipeline.p4, dash-pipeline/bmv2/stages/direction_lookup.p4, dash-pipeline/bmv2/stages/eni_lookup.p4, dash-pipeline/bmv2/stages/trusted_vni.p4, test/test-cases/functional/ptf/sai_dash_utils.py, test/test-cases/functional/ptf/saidashacl.py, test/test-cases/functional/ptf/saidashdpapp_sanity.py, test/test-cases/functional/ptf/saidashvnet.py, test/test-cases/functional/ptf/saidashvnet_sanity.py
Referring to https://github.com/sonic-net/SONiC/pull/1911 and https://github.com/sonic-net/DASH/pull/665, to support FNIC pipeline, this PR adds the followings:
- ENI mode VM, FNIC
- ENI drop counter `eni_trusted_vni_entry_miss_drop`
- Action `set_inbound_direction` is not defaultonly at table `direction_lookup`
- table `global_trusted_vni` and `eni_trusted_vni`
=> [dash-p4] Add ENI mode and trusted vni stage

.github/workflows/dash-bmv2-bldr-docker.yml, .github/workflows/dash-bmv2-ci.yml, .github/workflows/dash-dpdk-ci.yml, .github/workflows/dash-grpc1.43.2-docker.yml, .github/workflows/dash-p4c-bmv2-docker.yml, .github/workflows/dash-p4c-dpdk-docker.yml, .github/workflows/dash-saichallenger-client-bldr-docker.yml, .github/workflows/dash-saichallenger-client-docker.yml, .github/workflows/dash-saithrift-bldr-docker.yml, .github/workflows/dash-saithrift-client-bldr-docker.yml, .github/workflows/dash-saithrift-client-docker.yml
- Problem
All workflows are failing on ubuntu-20.04 runner. The reason is as below:
`This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101`
- Solution
Update the ubuntu version to ubuntu-22.04
=> [ci] Run github workflow on ubuntu-22.04 instead of ubuntu-20.04

dash-pipeline/SAI/templates/saifixedapis.cpp.j2
Those api will be needed when compiling sairedis syncd when DASH is enabled
=> [SAI] Add bulk get_stats and clear stats
